name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: node_modules Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install

      - name: Build web
        run: cd example &&  y | npx expo build:web

      - name: Deploy to github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: example/web-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
